### ISSUE TITLE
IntelliJ IDE error without 

### ISSUE THREAD

**Issue by jarnnk** [Genuitec/CodeTogether#360]
**Describe the bug**
When joining a hosted session in IntelliJ sometimes error messeges show up and the following error code is posted:
`java.lang.NullPointerException
	at com.genuitec.codetogether.services.EditorMonitor$3.reportIfNeeded(EditorMonitor.java:722)
	at com.genuitec.codetogether.services.EditorMonitor$3.afterAdded(EditorMonitor.java:705)
	at com.intellij.openapi.editor.impl.MarkupModelImpl.fireAfterAdded(MarkupModelImpl.java:277)
	at com.intellij.openapi.editor.impl.MarkupModelImpl.addRangeHighlighter(MarkupModelImpl.java:162)
	at com.intellij.openapi.editor.impl.MarkupModelImpl.addRangeHighlighterAndChangeAttributes(MarkupModelImpl.java:151)
	at com.intellij.codeInsight.daemon.impl.UpdateHighlightersUtil.createOrReuseHighlighterFor(UpdateHighlightersUtil.java:419)
	at com.intellij.codeInsight.daemon.impl.UpdateHighlightersUtil.addHighlighterToEditorIncrementally(UpdateHighlightersUtil.java:101)
	at com.intellij.codeInsight.daemon.impl.HighlightingSessionImpl.lambda$queueHighlightInfo$2(HighlightingSessionImpl.java:119)
	at com.intellij.codeInsight.daemon.impl.HighlightingSessionImpl.lambda$new$0(HighlightingSessionImpl.java:43)
	at com.intellij.util.containers.TransferToEDTQueue.processNext(TransferToEDTQueue.java:120)
	at com.intellij.util.containers.TransferToEDTQueue.access$300(TransferToEDTQueue.java:41)
	at com.intellij.util.containers.TransferToEDTQueue$1.run(TransferToEDTQueue.java:70)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:348)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:131)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:187)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)`

I don't know why this happens, everything seems to work properly.

**To Reproduce**
- Update to lastest 2022.1 release
- Edit .java Files in multiple tabs with 3 participants

**Expected behavior**

**Screenshots**

**CodeTogether Host**
 - IDE: [Eclipse]
 - IDE Version [2022.1]
 - OS: [Windows]
 - OS Version: [10]
 - not me

**IDE Participant**
 - IDE: [IntelliJ]
 - IDE Version [2022.1]
 - OS: [Gnome 41.3 + Linux]
 - OS Version: [Kernel 5.15.17]
 - OopenJDK: [java-17-openjdk]

**IDE Participant**
 - IDE: [Eclipse]
 - IDE Version [2022.1]
 - OS: [Windows]
 - OS Version: [10]
 - also not me
 
**Additional context**
I wish I could provide more information about this problem. I'm going to try reproducing it this week.

**Workaround (if any)**

**Comment by wgalanciak** [comment]
Thanks for reporting the issue. We are going to fix it for the upcoming release.

**Comment by jarnnk** [comment]
You may be right. I'll report about this later on this week.
