### ISSUE TITLE
[IntelliJ-Plugin] java.lang.AssertionError: Wrong line separators: '\r\n' at offset 0

### ISSUE THREAD

**Issue by nbeDPDHL** [Genuitec/CodeTogether#392]
**Describe the bug**
Using the IntelliJ Plugin, at some point it reported an error in the plugin (see the Screenshots).

java.lang.AssertionError: Wrong line separators: '\r\n' at offset 0
	at com.intellij.openapi.util.text.StringUtil.assertValidSeparators(StringUtil.java:2475)
	at com.intellij.openapi.editor.impl.DocumentImpl.assertValidSeparators(DocumentImpl.java:714)
	at com.intellij.openapi.editor.impl.DocumentImpl.replaceString(DocumentImpl.java:608)
	at com.intellij.openapi.editor.impl.DocumentImpl.replaceString(DocumentImpl.java:599)
	at com.genuitec.codetogether.util.DocumentTextWrapper$DoReplace.run(DocumentTextWrapper.java:29)
	at com.genuitec.codetogether.util.DocumentTextWrapper.lambda$finish$0(DocumentTextWrapper.java:101)
	at com.genuitec.codetogether.util.DocumentUtils.writeInReadOnlySession(DocumentUtils.java:27)
	at com.genuitec.codetogether.util.DocumentTextWrapper.lambda$finish$1(DocumentTextWrapper.java:94)
	at com.intellij.openapi.command.WriteCommandAction.lambda$runWriteCommandAction$4(WriteCommandAction.java:361)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.lambda$doRunWriteCommandAction$1(WriteCommandAction.java:150)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:947)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.lambda$doRunWriteCommandAction$2(WriteCommandAction.java:148)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:219)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:184)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.doRunWriteCommandAction(WriteCommandAction.java:157)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.run(WriteCommandAction.java:124)
	at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:361)
	at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:349)
	at com.genuitec.codetogether.util.DocumentTextWrapper.finish(DocumentTextWrapper.java:92)
	at com.genuitec.codetogether.idetoide.services.ClEditingEventsHandler.lambda$applyPatchAt$30(ClEditingEventsHandler.java:779)
	at com.genuitec.codetogether.idetoide.util.ClEditorLookup$LookupHolder.applyChange(ClEditorLookup.java:116)
	at com.genuitec.codetogether.idetoide.services.ClEditingEventsHandler.applyPatchAt(ClEditingEventsHandler.java:779)
	at com.genuitec.codetogether.idetoide.services.ClEditingEventsHandler.lambda$patched$24(ClEditingEventsHandler.java:508)
	at com.genuitec.codetogether.idetoide.services.ClEditingEventsHandler.lambda$runInEditor$38(ClEditingEventsHandler.java:1071)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:348)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:131)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:187)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**To Reproduce**
Unfortunately I cannot exactly what caused this. I was just watching a colleague editing a simple textfile and at some point the error showed up.

**Expected behavior**
No error should occur.

**Screenshots**
![image](https://user-images.githubusercontent.com/108811728/179974233-06263f6e-2384-44f0-ab53-b298ebee9dd9.png)

**CodeTogether Host**
 - IDE: IntelliJ
 - IDE Version 2022.1,2
 - OS: Windows
 - OS 10

**IDE Participant**
 - IDE: IntelliJ
 - IDE Version 2021.3.3
 - OS: Windows
 - OS Version: 10

**Comment by brianvfernandes** [comment]
Thank you for the report - I'm assuming this showed up in the guest IntelliJ IDE? Additionally, beyond the error being logged, how did this affect your session? For instance, did you lose synchronization, or did you have to reopen the file / restart the session in order to be able to continue?

**Comment by nbeDPDHL** [comment]
You are correct. In happened on the guest machine.
Apart from that error showing up, I don't remember anything else, but we didn't do a lot more in that session. So it might be possible that we lost sync and just didn't realize it. Sorry.
