### ISSUE TITLE
Intellij IDE Editor bug

### ISSUE THREAD

**Issue by ssmithstone** [Genuitec/CodeTogether#425]
**Describe the bug**
It's throwing the follow exception
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.genuitec.codetogether.ui.action.OpenGithubAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.genuitec.codetogether]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)

**To Reproduce**
Randomly occurs there is no session in progress, the error icon appears so i reported it

**Expected behavior**

**Screenshots**

**CodeTogether Host**
 - IDE: IntelliJ
 - IDE Version 2024.
 - OS: maxos
 - OS Version: 14.4.1

**Comment by wgalanciak** [comment]
Thanks for reporting the issue. We are going to address it in the upcoming release.
