### ISSUE TITLE
`java.lang.IllegalArgumentException: Illegal transform definition 'rotate(360deg)' encountered error while parsing 'rotate(360deg)'`

### ISSUE THREAD

**Issue by rakleed** [Genuitec/CodeTogether#432]
When the second participant disconnected from the web interface.

```log
java.lang.IllegalArgumentException: Illegal transform definition 'rotate(360deg)' encountered error while parsing 'rotate(360deg)'
	at com.github.weisj.jsvg.attributes.AttributeParser.parseTransform(SourceFile:238)
	at com.github.weisj.jsvg.parser.AttributeNode.g(SourceFile:285)
	at com.github.weisj.jsvg.ci.a(SourceFile:63)
	at com.github.weisj.jsvg.bn.build(SourceFile:54)
	at com.github.weisj.jsvg.bl.build(SourceFile:64)
	at com.github.weisj.jsvg.bm.build(SourceFile:70)
	at com.github.weisj.jsvg.nodes.SVG.build(SourceFile:104)
	at com.github.weisj.jsvg.parser.ParsedElement.build(SourceFile:115)
	at com.intellij.ui.svg.JSvgDocumentFactoryKt.buildDocument(JSvgDocumentFactory.kt:110)
	at com.intellij.ui.svg.JSvgDocumentFactoryKt.createJSvgDocument(JSvgDocumentFactory.kt:37)
	at com.intellij.ui.svg.JSvgDocumentFactoryKt.createJSvgDocument$default(JSvgDocumentFactory.kt:35)
	at com.intellij.ui.svg.JSvgDocumentFactoryKt.createJSvgDocument(JSvgDocumentFactory.kt:30)
	at com.intellij.ui.svg.SvgKt.renderImage(svg.kt:285)
	at com.intellij.ui.svg.SvgKt.renderAndCache(svg.kt:258)
	at com.intellij.ui.svg.SvgKt.access$renderAndCache(svg.kt:1)
	at com.intellij.ui.svg.SvgKt.loadSvgAndCacheIfApplicable-F6nGey4(svg.kt:567)
	at com.intellij.ui.icons.ImageCacheKt.doLoadByDescriptor(imageCache.kt:241)
	at com.intellij.ui.icons.ImageCacheKt.loadByDescriptorWithoutCache(imageCache.kt:148)
	at com.intellij.ui.icons.ImageCacheKt.loadImage(imageCache.kt:111)
	at com.intellij.ui.icons.ImageCacheKt.loadImage$default(imageCache.kt:64)
	at com.intellij.ui.icons.ImageDataByPathResourceLoader.loadImage(ImageDataByUrlLoader.kt:67)
	at com.intellij.ui.icons.CachedImageIcon.loadImage-Xbo1f9k$intellij_platform_util_ui(CachedImageIcon.kt:330)
	at com.intellij.ui.icons.ScaledIconCache.loadIcon-GvFvY-8(ScaledIconCache.kt:58)
	at com.intellij.ui.icons.ScaledIconCache.getCachedIcon-BVbfYdY(ScaledIconCache.kt:43)
	at com.intellij.ui.icons.CachedImageIcon.resolveActualIcon(CachedImageIcon.kt:166)
	at com.intellij.ui.icons.CachedImageIcon.getIconWidth(CachedImageIcon.kt:127)
	at com.genuitec.codetogether.ui.tree.StyledTreeCellRenderer.paintComponent(StyledTreeCellRenderer.java:185)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.CellRendererPane.paintComponent(CellRendererPane.java:170)
	at com.intellij.ui.tree.ui.DefaultTreeUI.paint(DefaultTreeUI.java:373)
	at java.desktop/javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at java.desktop/javax.swing.JComponent.paintComponent(JComponent.java:855)
	at com.intellij.ui.treeStructure.Tree.paintComponent(Tree.java:379)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at com.intellij.ui.treeStructure.Tree.paint(Tree.java:310)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:964)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1133)
	at java.desktop/javax.swing.JViewport.paint(JViewport.java:736)
	at com.intellij.ui.components.JBViewport.paint(JBViewport.java:240)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5319)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1680)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1655)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1592)
	at java.desktop/javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:272)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1352)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5267)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5077)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:887)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:870)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:870)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:843)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:789)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1921)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:750)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:696)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$16(IdeEventQueue.kt:590)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWithoutImplicitRead(AnyThreadWriteThreadingSupport.kt:117)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:590)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:73)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1$1.compute(IdeEventQueue.kt:357)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1$1.compute(IdeEventQueue.kt:356)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:843)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.invoke(IdeEventQueue.kt:356)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.invoke(IdeEventQueue.kt:351)
	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke$lambda$0(IdeEventQueue.kt:1035)
	at com.intellij.openapi.application.WriteIntentReadAction.lambda$run$0(WriteIntentReadAction.java:24)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:84)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteIntentReadAction(ApplicationImpl.java:910)
	at com.intellij.openapi.application.WriteIntentReadAction.compute(WriteIntentReadAction.java:55)
	at com.intellij.openapi.application.WriteIntentReadAction.run(WriteIntentReadAction.java:23)
	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke(IdeEventQueue.kt:1035)
	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke(IdeEventQueue.kt:1035)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1036)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1036)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$10(IdeEventQueue.kt:351)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:389)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.IllegalStateException: Unexpected token '' rest=deg(index=3 in input=360deg)
	at com.github.weisj.jsvg.dk.i(SourceFile:98)
	at com.github.weisj.jsvg.attributes.AttributeParser.parseDoubleList(SourceFile:161)
	at com.github.weisj.jsvg.attributes.AttributeParser.parseTransform(SourceFile:1250)
	... 90 more
Caused by: java.lang.NumberFormatException: empty String
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842)
	at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.base/java.lang.Double.parseDouble(Double.java:792)
	at com.github.weisj.jsvg.dk.i(SourceFile:93)
	... 92 more
```

```
WebStorm 2024.2.1
Build #WS-242.21829.149, built on August 29, 2024
Licensed to Pavel Moiseenko
Subscription is active until August 28, 2025.
For educational use only.
Runtime version: 21.0.3+13-b509.11 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 14.6.1
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 12
Metal Rendering is ON
Registry:
  debugger.new.tool.window.layout=true
  vcs.log.index.enable=true
  ide.experimental.ui=true
  i18n.locale=
  terminal.new.ui=true
  ide.images.show.chessboard=true
Non-Bundled Plugins:
  com.pixelperfect.npm-package-json (2023.0.8)
  com.nasller.CodeGlancePro (1.9.0)
  com.wakatime.intellij.plugin (15.0.2)
  com.intellij.ml.llm (242.21829.142)
  com.intellij.grazie.pro (0.3.326)
  org.jetbrains.plugins.gitlab (242.21829.162)
  org.jetbrains.plugins.github (242.21829.162)
  com.atlassian.bitbucket.references (2023.1.301)
  com.haulmont.rcb (242.20224.155)
  com.github.copilot (1.5.20.6554)
  ee.carlrobert.chatgpt (2.10.2-241.1)
  zielu.gittoolbox (500.2.15+242)
  com.genuitec.codetogether (2024.3.1-01618)

```

**Comment by weisJ** [comment]
This is due to some invalid svg trying to get rendered. The SVG specification does not allow `deg` units in `rotate` transform values. Fix is to remove `rotate(360deg)` from the offending SVG file (as rotating by 360 degree does nothing anyway.
